package models

type Peer struct {
	ID       string                 `json:"peerID"`
	RawMap   map[string]interface{} `json:"profile"`
	LastPing int64                  `json:"lastPing"`
}

/**

slug          string    `json:"slug"`
AverageRating int64     `json:"averageRating"`
Hash          string    `json:"hash"`
Language      string    `json:"language"`
Nsfw          bool      `json:"nsfw"`
RatingCount   int64     `json:"ratingCount"`
Thumbnail     Thumbnail `json:"thumbnail"`
PeerSlug      string    `json:"peerSlug"`
ParentPeer    string    `json:"parentPeer"`
*/
// Generated by https://quicktype.io

type Listing struct {
	Slug          string    `json:"slug"`
	AverageRating int64     `json:"averageRating"`
	Hash          string    `json:"hash"`
	Language      string    `json:"language"`
	Nsfw          bool      `json:"nsfw"`
	RatingCount   int64     `json:"ratingCount"`
	Thumbnail     Thumbnail `json:"thumbnail"`
	PeerSlug      string    `json:"peerSlug"`
	ParentPeer    string    `json:"parentPeer"`
	Location      Location  `json:"location"`
}

type IPFSListing struct {
	Listing   ListingClass `json:"listing"`
	Signature string       `json:"signature"`
}

type ListingClass struct {
	Slug               string           `json:"slug"`
	VendorID           VendorID         `json:"vendorID"`
	Metadata           Metadata         `json:"metadata"`
	Item               Item             `json:"item"`
	ShippingOptions    []ShippingOption `json:"shippingOptions"`
	Taxes              []interface{}    `json:"taxes"`
	Coupons            []interface{}    `json:"coupons"`
	Moderators         []string         `json:"moderators"`
	TermsAndConditions string           `json:"termsAndConditions"`
	RefundPolicy       string           `json:"refundPolicy"`

	AverageRating int64     `json:"averageRating"`
	Hash          string    `json:"hash"`
	Language      string    `json:"language"`
	Nsfw          bool      `json:"nsfw"`
	RatingCount   int64     `json:"ratingCount"`
	Thumbnail     Thumbnail `json:"thumbnail"`
	PeerSlug      string    `json:"peerSlug"`
	ParentPeer    string    `json:"parentPeer"`
	Location      Location  `json:"location"`
}

type Item struct {
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	ProcessingTime string   `json:"processingTime"`
	Price          int64    `json:"price"`
	Tags           []string `json:"tags"`
	Images         []Image  `json:"images"`
	Categories     []string `json:"categories"`
	Condition      string   `json:"condition"`
	Options        []Option `json:"options"`
	Skus           []Skus   `json:"skus"`
}

type Image struct {
	Filename string `json:"filename"`
	Original string `json:"original"`
	Large    string `json:"large"`
	Medium   string `json:"medium"`
	Small    string `json:"small"`
	Tiny     string `json:"tiny"`
}

type Option struct {
	Name     string    `json:"name"`
	Variants []Variant `json:"variants"`
}

type Variant struct {
	Name string `json:"name"`
}

type Skus struct {
	VariantCombo []int64 `json:"variantCombo"`
}

type Metadata struct {
	Version            int64    `json:"version"`
	ContractType       string   `json:"contractType"`
	Format             string   `json:"format"`
	Expiry             string   `json:"expiry"`
	AcceptedCurrencies []string `json:"acceptedCurrencies"`
	PricingCurrency    string   `json:"pricingCurrency"`
	EscrowTimeoutHours int64    `json:"escrowTimeoutHours"`
}

type ShippingOption struct {
	Name     string    `json:"name"`
	Type     string    `json:"type"`
	Regions  []string  `json:"regions"`
	Services []Service `json:"services"`
}

type Service struct {
	Name                string `json:"name"`
	EstimatedDelivery   string `json:"estimatedDelivery"`
	Price               *int64 `json:"price,omitempty"`
	AdditionalItemPrice *int64 `json:"additionalItemPrice,omitempty"`
}

type VendorID struct {
	PeerID     string  `json:"peerID"`
	Pubkeys    Pubkeys `json:"pubkeys"`
	BitcoinSig string  `json:"bitcoinSig"`
}

type Pubkeys struct {
	Identity string `json:"identity"`
	Bitcoin  string `json:"bitcoin"`
}

type Location struct {
	AddressOne string `json:"addressOne"`
	AddressTwo string `json:"addressTwo"`
	City       string `json:"city"`
	Country    string `json:"country"`
	Latitude   string `json:"latitude"`
	Longitude  string `json:"longitude"`
	PlusCode   string `json:"plusCode"`
	State      string `json:"state"`
	ZipCode    string `json:"zipCode"`
}

type AdvancedSearchQuery struct {
	Query      string        `json:"query"`
	Filters    []string      `json:"filters"`
	Limit      int           `json:"limit"`
	Start      int           `json:"start"`
	Transforms []interface{} `json:"transforms"`
	Sort       string        `json:"sort"`
}

// Probably Remove everything beyond this block in the future

type OldListing struct {
	AcceptedCurrencies []string      `json:"acceptedCurrencies"`
	AverageRating      int64         `json:"averageRating"`
	Categories         []string      `json:"categories"`
	ContractType       string        `json:"contractType"`
	Description        string        `json:"description"`
	Hash               string        `json:"hash"`
	Language           string        `json:"language"`
	Location           Location      `json:"location"`
	Moderators         []interface{} `json:"moderators"`
	Nsfw               bool          `json:"nsfw"`
	Price              Price         `json:"price"`
	RatingCount        int64         `json:"ratingCount"`
	Slug               string        `json:"slug"`
	Thumbnail          Thumbnail     `json:"thumbnail"`
	Title              string        `json:"title"`
}

type PubKeys struct {
	Identity string `json:"identity"`
	bitcoin  string `json:"bitcon"`
}

type Price struct {
	Amount       int64  `json:"amount"`
	CurrencyCode string `json:"currencyCode"`
	Modifier     int64  `json:"modifier"`
}

type Thumbnail struct {
	Medium string `json:"medium"`
	Small  string `json:"small"`
	Tiny   string `json:"tiny"`
}
